# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
    - template: 'Infrastructure\tree\main\Azure\Orchestrator\var.yml@onoipor1'
pool:
  vmImage: 'Windows-latest'
steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: '$(SubscriptionID)'
    scriptLocation: inlineScript
    inlineScript: |
     mkdir $(System.ArtifactsDirectory)\BlobFile
     az storage blob download-batch -d $(System.ArtifactsDirectory)\BlobFile --pattern *.zip -s $(containername) --account-key $(accountkey) --account-name $(accountname)

- task: AzurePowerShell@5
  inputs:
    azureSubscription: '$(SubscriptionID)'
    AzurePowerShellVersion: 'LatestVersion'
    ScriptType: 'FilePath'
    ScriptPath: '$(System.DefaultWorkingDirectory)\Azure\Orchestrator\20.10.1\Deploy-UiPathOrchestratorPaaS.ps1'
    ScriptArguments:
     -azureSubscriptionId $(SubscriptionID)
     -azureTenantId $(TENANTID)
     -resourceGroupName $(RGNAME)
     -appServiceNameOrch $(ORCHNAME)
     -appServiceNameIdentity $(IDNAME)
     -appServiceNameWebhooks $(WEBHOOKNAME)
     -hostAdminPassword $(ORCHPASSWORD)
     -defaultTenantAdminPassword $(ORCHPASSWORD)
     -storageLocation $(STORAGELOCATION)
     -identityServerUrl $(identityurl)
     -orchestratorUrl $(ORCHURL)
     -action Deploy

